config/routes.rb
Rails.application.routes.draw do
  resources :widgets

  root 'welcome#index'

  get 'signup', to: 'welcome/signup', controller: 'welcome'

  get 'callback', to: 'welcome/callback', controller: 'welcome'

  get 'success', to: 'welcome/callback', controller: 'welcome'

  get 'camo', to: 'welcome/camo', controller: 'welcome'

  get 'delete_account', to: 'welcome/delete_account', controller: 'welcome'

  post 'add_premium_email', to: 'welcome/add_premium_email', controller: 'welcome'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/premium_email.rb
class PremiumEmail < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  # Homepage
  def index
  end

  # This is called by the 'Sign Up with GitHub' buttons
  def signup
  	authorize()
  end

  def authorize
  	if Rails.env == "development"
  		address = github.authorize_url scope: 'public_repo'
    	redirect_to address
  	elsif Rails.env == "production"
    	address = github.authorize_url redirect_uri: 'http://www.githubgardener.xyz/callback', scope: 'public_repo'
    	redirect_to address
  	end
  end

  # This is called by the GitHub API after user agrees to authorize the app. It is also called when he clicks 'Sign Up with Github', even if he has already authorize it
  def callback
  	begin

  		# Get the authentication token
  		authorization_code = params[:code]
	    @access_token = github.get_token authorization_code
	    @access_token.token
		
		  # Get GitHub username
		  uri = URI('https://api.github.com/user?access_token='+@access_token.token)
		  response = JSON.parse(Net::HTTP.get(uri))
		  username = response['login']

		  github = Github.new oauth_token: @access_token.token

	    # Create the new User if he isn't doesn't already exist, else update the authentication token
	    user = User.where(:github_username => username).first

	    if user == nil

	    	# Create new user
	    	user = User.new(:github_username => username, :github_authentication_token => @access_token.token)
	    	user.save

	    	create_repo_and_initial_commit(username, @access_token.token, github)

	    else
        create_repo_and_initial_commit(username, @access_token.token, github)
	    	# Update authentication token
	    	user.github_authentication_token = @access_token.token
	    	user.save

	    end

	# Catch error so that the page does not return a 500 error
	rescue Github::Error::GithubError => e
	  	puts e.message
	  	if e.is_a? Github::Error::ServiceError
	    	puts 'service error'
	  	elsif e.is_a? Github::Error::ClientError
	  		puts 'client error'
	  	end
	end

	session[:access_token] = @access_token.token
	redirect_to "/success"  
  
  end

  def camo

  end

  def delete_account

	   user = User.where(:github_authentication_token => session[:access_token]).first
  	
    if user!=nil
	   user.destroy
    end
  
  end

  def add_premium_email
    email = PremiumEmail.new(:email => params[:email])
    email.save
  end

  private

  	

  	def create_repo_and_initial_commit(username, token, github)

      begin
  		  # Create a repo, github-gardener + a random number to be sure the name does not exist. Statistically speaking, it is good enough
  		  repo_name = 'github-gardener'
  	    github.repos.create name: repo_name

  	    # Update repo_name field
  	    user = User.where(:github_username => username).first
  	    user.repo_name = repo_name
  	    user.save

  	    # Create a new file, README.md and commit
  	    github.repos.contents.create username, user.repo_name, 'README.md',
  			  path: 'README.md',
  			  message: 'Initial commit',
  			  content: "This is the GitHub Gardener project"

      rescue Github::Error::GithubError => e
        puts e.message
        if e.is_a? Github::Error::ServiceError
          puts 'service error'
        elsif e.is_a? Github::Error::ClientError
          puts 'client error'
        end
      end

  	 end

   def github
   	
   	# Instantiate 'GitHub Gardener'
   	# For development purposes, I have two apps, 'Get GitHub Gardener' and 'Get GitHub Gardener Dev'
   	if Rails.env == "development"
    
    	# Get GitHub Gardener Dev
    	@github ||= Github.new client_id: ENV.fetch('GITHUB_CLIENT_ID'), client_secret: ENV.fetch('GITHUB_CLIENT_SECRET')
  	
  	elsif Rails.env == "production"
    	
    	# Get GitHub Gardener
    	@github ||= Github.new client_id: ENV.fetch('GITHUB_CLIENT_ID'), client_secret: ENV.fetch('GITHUB_CLIENT_SECRET')
  	
  	end
   end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitHub Gardener | Watch your GitHub turn green in the span of a year</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag  '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="https://i.imgur.com/VsM2haI.png">
  <link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono|Roboto:400,500,700" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-static-top" style=" border: none; background-color: white; margin-top: 10px; margin-left: 30px; margin-right: 30px; font-size: 16px;">
        <div class="container-fluid">
          <div class="navbar-header" style="margin-top: 10px;">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar" style="background-color: black;"></span>
              <span class="icon-bar" style="background-color: black;"></span>
              <span class="icon-bar" style="background-color: black;"></span>
            </button>
            <a style="color:green; font-size:18px;" href="/"><b>GitHub Gardener</b></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
    
            <ul class="nav navbar-nav navbar-right">
              <li class="">
                <a style="color: grey;" href="/#howdoesitwork"> How does it work?</a>
              </li>
              <li class="">
                <a style="color: grey;" href="/#open_source"> Open Source</a>
              </li>
              <li class="">
                <a style="color: grey;" href="/#built_in_the_open"> Built in the Open</a>
              </li>
              <li class="">
                <a style="color: grey;" href="/#pricing"> Pricing</a>
              </li>
              <li class="">
                <a class="btn" style="border-color: green; border-radius: 10px; border-width: 1.5px; font-size: 16px; color: grey;" href="/signup"> Sign Up with GitHub</a>
              </li>
            </ul>
          </div>
        </div>
      
</nav>

<%= yield %>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-119126879-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-119126879-1');
    </script>
</body>
</html>

app/views/welcome/add_premium_email.html.erb
<header>
  <div style=" background: url() ; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 100vh;
        text-align: center;
        font-family: 'Roboto'">
        <h2 style="color:#191919; margin-top: 100px;">Perfect! You will notified when the premium version is ready! 🎉</h2>
        <p style="color:grey; font-size: 19px;">You can go on and use the Regular version for now..</p><br><br>

      <a href="/" style="border-radius: 10px; color: white; text-decoration: none; padding:10px; font-size: 16px;" class="btn btn-success">Go back to homepage</a>


    </div>
</header>

app/views/welcome/callback.html.erb
<p>Hi <%= @access_token.token %></p>

app/views/welcome/camo.html.erb
<header>
  <div style=" background: url() ; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 100vh;
        text-align: center;
        font-family: 'Roboto'">
        <h2 style="color:#191919; margin-top: 100px;">Oops.. You came here too early! 😁</h2>
        <p style="color:grey; font-size: 19px;">I haven't built this feature yet. If I see interest, I will most certainly build it for you all! ❤️<br>GitHub Gardener is only one week old! You can see the whole story <a target="_blank" href="https://twitter.com/alexsideris_/status/993523095708332032" style="">here</a>.</p><br><br>

        <div style="background-color: #2F4F4F; padding:20px;">
            <%= form_tag '/add_premium_email' do%>
                <p style="color:white; font-size: 19px;">Get notified first when I build it!</p>
                <%= text_field_tag 'email', '', :style => "width:300px; height:40px; font-size: 19px; color:grey;", :type => 'email', :placeholder => ' Your email address'%></br><br>
                <%= submit_tag "submit",:value => "Let me know when it's ready!", :class => 'btn btn-success', :style => 'padding:10px;' %>
            <%end%>
        </div>
            <br><br><br>

      <a href="/" style="border-radius: 10px; color: black; text-decoration: none; padding:10px; font-size: 16px;" class="btn btn-default">Go back to homepage</a>


    </div>
</header>

app/views/welcome/delete_account.html.erb
<header>
  <div style=" background: url() ; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 100vh;
        text-align: center;
        font-family: 'Roboto'">
        <h2 style="color:#191919; margin-top: 100px; margin-bottom: 40px;">Sorry to see you go.. 😢</h2>
        <p style="color:grey; font-size: 19px;">I have deleted your account and GitHub Gardener will not commit any more to your GitHub account</p>
    </div>
</header>

app/views/welcome/index.erb
<header>
  <div style=" background: url() ; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 100vh;
        color: #fff;
        text-align: center;
        font-family: 'Roboto'">
    <img src="https://i.imgur.com/VsM2haI.png" style="height: 250px; margin-top: 50px;">
      <p style="margin-top:30px; color: green; font-size: 50px;">GitHub Gardener</p>
      <p style="margin-bottom:30px; color: #696969; font-size: 18px;">Daily, automated commits that magically turn your GitHub green</p>
      <a target="_blank" href="https://github.com/alexandersideris/make-my-github-green" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-bottom: 10px;"><span class="glyphicon glyphicon-eye-open"></span> View Code on GitHub</a>
      <a href="/signup" style="border-radius: 10px; color: white; text-decoration: none; padding:10px; font-size: 16px; margin-bottom: 10px;" class="btn btn-success"><span class="glyphicon glyphicon-user"></span> Sign Up with GitHub</a>
      
  </div>

</header>

<div id="howdoesitwork" style="text-align: center; font-family: 'Roboto'; margin-top: 80px;">

  <h2 style="margin-bottom:50px;">Watch your GitHub magically turn green</h2>
  <div class="row">
    <div class="col col-md-2"></div>
    <div class="col col-md-8">
      <img src="https://raw.githubusercontent.com/maelsan/faker-push/master/medias/green.png?token=AGyZ7Ob2A7OTZS1TMZLvCGZdxNS1TM4Cks5XeXVYwA%3D%3D" style="width: 100%; margin:auto;"/>
    </div>
    <div class="col col-md-2">
    </div>
  </div>

  <h2 style="margin-top:100px; margin-bottom: 75px;">How does it work?</h2>
  <p style="font-size: 18px; margin:40px;"><span style="color:#5cb85c;">1) </span>When you sign up, GitHub Gardener will create a new repository for you</p>
  <p style="font-size: 18px; margin:40px;"><span style="color:#5cb85c;">2) </span>GitHub Gardener will commit to the new repository a random number of times daily</p>
  <p style="font-size: 18px; margin:40px;"><span style="color:#5cb85c;">3) </span>Watch your GitHub turn green over the span of a year</p>

</div>

<div id="open_source" style="text-align: center; font-family: 'Roboto'">

  <h2 style="margin-top:100px; margin-bottom: 50px;">Open Source</h2>
  <div class="row">
    <div class="col col-md-2"></div>
    <div class="col col-md-8">
      <img src="https://i.imgur.com/ydxPRlR.png" style="height:150px; margin:auto;"/>
    </div>
    <div class="col col-md-2">
    </div>
  </div>
  <a target="_blank" href="https://github.com/alexandersideris/make-my-github-green" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-top: 40px;"><span class="glyphicon glyphicon-eye-open"></span> View Code on GitHub</a>
  <p style="font-size: 18px; margin:40px;">While building GitHub Gardener, I found that I needed full read and write access to the user's public repos</p>
  <p style="font-size: 18px; margin:40px;">I understand that it might be too much to ask for, given that it is a very simple service</p>
  <p style="font-size: 18px; margin:40px;">In order to create a sense of security and show my pure intentions, I decided to open source it</p>

</div>

<div id="built_in_the_open" style="text-align: center; font-family: 'Roboto'">

  <h2 style="margin-top:100px; margin-bottom: 50px;">Built in the Open</h2>
  <div class="row">
    <div class="col col-md-2"></div>
    <div class="col col-md-8">
      <img src="https://i.imgur.com/ZpQ2T2Y.png" style="height:150px; margin:auto;"/>
    </div>
    <div class="col col-md-2">
    </div>
  </div>
  <a target="_blank" href="https://twitter.com/alexsideris_/status/993523095708332032" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-top: 40px;"><span class="glyphicon glyphicon-eye-open"></span> View Story on Twitter</a>
  <a target="_blank" href="https://wip.chat/products/1367" class="btn btn-default" style="border-radius: 10px; border-color: #424242; color: black; text-decoration: none; padding:10px; font-size: 16px; margin-right:10px; margin-top: 40px;"><span class="glyphicon glyphicon-eye-open"></span> View Progress on WIP</a>
  <p style="font-size: 18px; margin:40px;">The complete story, from idea conception to launch can be found on a single twitter thread</p>
  <p style="font-size: 18px; margin:40px;">You can also view all my public todos on WIP</p>

</div>

<div id="pricing" style="margin-top: 100px; text-align: center; margin-bottom: 400px;">
  <h2 style="margin-bottom: 75px;">Pricing</h2>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4" style="padding:33px; text-align: center; margin-bottom: 100px;">
      <div class="card h-100" style="-moz-border-radius: 6px; 
 border-radius: 16px; border-color: grey; border-width: 1px;">

        <div class="card-body" style="height:300px;">
          <h4 class="card-title" style="margin-top: 10px; margin-bottom: 30px;">
            <p style="color: #191919; font-size: 32px;"><img src="https://png.icons8.com/color/1600/person-male.png" style="height:40px;" /><b> Regular</b></p>
          </h4>
          <hr>
          <p style="font-size: 20px;"><b>Free</b></p>
          <hr>                   
          <p style="color: grey;" class="card-text">Just a regular guy</p>
          <p style="font-size: 16px;"><b>Features</b></p>
          <ul>
            <li>
              <p style="font-size: 14px; color:#191919">
              Standard repository name
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              A repository with a README file
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              0 to 7 commits per day
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Basic commits and commit messages
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              All commits happen at the same time
              </p>
            </li>
          </ul>
          <a href="/signup" style="border-radius: 10px; color: white; text-decoration: none; font-size: 16px; width:80%; margin-top: 20px;" class="btn btn-success"></span> Subscribe</a>
        </div>
                            
                            
      </div>
    </div>
    <div class="col-lg-4" style="padding:33px; text-align: center; margin-bottom: 100px;">
      <div class="card h-100" style="">

        <div class="card-body" style="height:300px;">
          <h4 class="card-title" style="margin-top: 10px; margin-bottom: 30px;">
            <p style="color: #191919; font-size: 32px;"><img src="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/512x512/soldier.png" style="height:40px;" /><b> Camo</b></p>
          </h4>
          <hr>
          <p style="font-size: 20px;"><b>20 $/year</b></p>
          <hr>                          
          <p style="color: grey;" class="card-text">Wait.. I can't see you</p>
          <p style="font-size: 16px;"><b>Features</b></p>
          <ul>
            <li>
              <p style="font-size: 14px; color:#191919">
              Custom repository name
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Full blown web app, choose your framework
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Custom number of commits per day
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Commits and commit messages are super realistic
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Commits are spread out throughout the day
              </p>
            </li>
          </ul>
          <a href="/camo" style="border-radius: 10px; color: white; text-decoration: none; font-size: 16px; width:80%; margin-top: 20px;" class="btn btn-success"></span> Subscribe</a>

        </div>
                            
                            
      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>

app/views/welcome/success.html.erb
<header>
  <div style=" background: url() ; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        height: 100vh;
        text-align: center;
        font-family: 'Roboto'">
        <h2 style="color:#191919; margin-top: 100px;">You have successfully signed up for GitHub Gardener! 🎉</h2>
        <p style="color:grey; font-size: 19px;">Now, all you have to do is wait for it to, slowly but surely, turn green..!</p>
        <img src="https://i.imgur.com/VJzmBo9.png" style="height:80px;" />
        
        <div id="pricing" style="margin-top: 120px; text-align: center; margin-bottom: 400px;">
  <p style="color:grey; font-size: 16px;">Don't forget!</p>
        <p style="color:grey; font-size: 16px;">You can always upgrade to Camo!</p>
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-4" style="padding:33px; text-align: center; margin-bottom: 100px;">
      <div class="card h-100" style="-moz-border-radius: 6px; 
 border-radius: 16px; border-color: grey; border-width: 1px;">

        <div class="card-body" style="height:300px;">
          <h4 class="card-title" style="margin-top: 10px; margin-bottom: 30px;">
            <p style="color: #191919; font-size: 32px;"><img src="https://png.icons8.com/color/1600/person-male.png" style="height:40px;" /><b> Regular</b></p>
          </h4>
          <hr>
          <p style="font-size: 20px;"><b>Free</b></p>
          <hr>                   
          <p style="color: grey;" class="card-text">Just a regular guy</p>
          <p style="font-size: 16px;"><b>Features</b></p>
          <ul>
            <li>
              <p style="font-size: 14px; color:#191919">
              Standard repository name
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              A repository with a README file
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              0 to 7 commits per day
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Basic commits and commit messages
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              All commits happen at the same time
              </p>
            </li>
          </ul>
          <a href="/signup" style="border-radius: 10px; color: grey; text-decoration: none; border-color:grey; border-width: 1px; font-size: 16px; width:80%; margin-top: 20px;" class="btn" disabled></span> Your current plan</a>

        </div>
                            
                            
      </div>
    </div>
    <div class="col-lg-4" style="padding:33px; text-align: center; margin-bottom: 100px;">
      <div class="card h-100" style="">

        <div class="card-body" style="height:300px;">
          <h4 class="card-title" style="margin-top: 10px; margin-bottom: 30px;">
            <p style="color: #191919; font-size: 32px;"><img src="https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/512x512/soldier.png" style="height:40px;" /><b> Camo</b></p>
          </h4>
          <hr>
          <p style="font-size: 20px;"><b>20 $/year</b></p>
          <hr>                          
          <p style="color: grey;" class="card-text">Wait.. I can't see you</p>
          <p style="font-size: 16px;"><b>Features</b></p>
          <ul>
            <li>
              <p style="font-size: 14px; color:#191919">
              Custom repository name
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Full blown web app, choose your framework
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Custom number of commits per day
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Commits and commit messages are super realistic
              </p>
            </li>
            <li>
              <p style="font-size: 14px; color:#191919">
              Commits are spread out throughout the day
              </p>
            </li>
          </ul>
          <a href="/camo" style="border-radius: 10px; color: white; text-decoration: none; font-size: 16px; width:80%; margin-top: 20px;" class="btn btn-success"></span> Upgrade to Camo</a>

        </div>
                            
                            
      </div>
    </div>
    <div class="col-lg-2"></div>
  </div>
</div>
	<p style="color:grey">I would hate to see you go, but you can unsubscribe from GitHub Gardener by clicking the button below 😢</p>
  	<a href="/delete_account" class="btn btn-danger" style="font-size: 11px;">Delete my account</a>
</div>

</header>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<div class="container">

<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

</div>

app/views/widgets/index.html.erb
<div class="container">
<h1>Listing widgets</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

</div>

app/views/widgets/new.html.erb
<div class="container">

<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

</div>

app/views/widgets/show.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>

</div>